export const recipes = [
  {
    vegetarian: true,
    vegan: false,
    glutenFree: false,
    dairyFree: false,
    veryHealthy: false,
    cheap: false,
    veryPopular: false,
    sustainable: false,
    lowFodmap: false,
    weightWatcherSmartPoints: 10,
    gaps: 'no',
    preparationMinutes: -1,
    cookingMinutes: -1,
    aggregateLikes: 40,
    healthScore: 1,
    creditsText: 'Foodista.com – The Cooking Encyclopedia Everyone Can Edit',
    license: 'CC BY 3.0',
    sourceName: 'Foodista',
    pricePerServing: 154.7,
    extendedIngredients: [
      {
        id: 1001,
        aisle: 'Milk, Eggs, Other Dairy',
        image: 'butter-sliced.jpg',
        consistency: 'SOLID',
        name: 'butter',
        nameClean: 'butter',
        original: '1 teaspoon butter',
        originalName: 'butter',
        amount: 1.0,
        unit: 'teaspoon',
        meta: [],
        measures: {
          us: {
            amount: 1.0,
            unitShort: 'tsp',
            unitLong: 'teaspoon',
          },
          metric: {
            amount: 1.0,
            unitShort: 'tsp',
            unitLong: 'teaspoon',
          },
        },
      },
      {
        id: 1011053,
        aisle: 'Milk, Eggs, Other Dairy',
        image: 'white-cream.png',
        consistency: 'LIQUID',
        name: 'double cream',
        nameClean: 'double cream',
        original: '2 tablespoons double cream',
        originalName: 'double cream',
        amount: 2.0,
        unit: 'tablespoons',
        meta: [],
        measures: {
          us: {
            amount: 2.0,
            unitShort: 'Tbsps',
            unitLong: 'Tbsps',
          },
          metric: {
            amount: 2.0,
            unitShort: 'Tbsps',
            unitLong: 'Tbsps',
          },
        },
      },
      {
        id: 1123,
        aisle: 'Milk, Eggs, Other Dairy',
        image: 'egg.png',
        consistency: 'SOLID',
        name: 'egg',
        nameClean: 'egg',
        original: '1 large egg, lightly beaten',
        originalName: 'egg, lightly beaten',
        amount: 1.0,
        unit: 'large',
        meta: ['lightly beaten'],
        measures: {
          us: {
            amount: 1.0,
            unitShort: 'large',
            unitLong: 'large',
          },
          metric: {
            amount: 1.0,
            unitShort: 'large',
            unitLong: 'large',
          },
        },
      },
      {
        id: 20081,
        aisle: 'Baking',
        image: 'flour.png',
        consistency: 'SOLID',
        name: 'flour',
        nameClean: 'wheat flour',
        original: '1 cup flour',
        originalName: 'flour',
        amount: 1.0,
        unit: 'cup',
        meta: [],
        measures: {
          us: {
            amount: 1.0,
            unitShort: 'cup',
            unitLong: 'cup',
          },
          metric: {
            amount: 125.0,
            unitShort: 'g',
            unitLong: 'grams',
          },
        },
      },
      {
        id: 1089003,
        aisle: 'Produce',
        image: 'grannysmith-apple.png',
        consistency: 'SOLID',
        name: 'granny smith apples',
        nameClean: 'granny smith apple',
        original: '2 Granny Smith apples chopped',
        originalName: 'Granny Smith apples chopped',
        amount: 2.0,
        unit: '',
        meta: ['chopped'],
        measures: {
          us: {
            amount: 2.0,
            unitShort: '',
            unitLong: '',
          },
          metric: {
            amount: 2.0,
            unitShort: '',
            unitLong: '',
          },
        },
      },
      {
        id: 93740,
        aisle: 'Gluten Free;Health Foods',
        image: 'almond-meal-or-almond-flour.jpg',
        consistency: 'SOLID',
        name: 'ground almonds',
        nameClean: 'almond meal',
        original: '50g ground almonds',
        originalName: 'ground almonds',
        amount: 50.0,
        unit: 'g',
        meta: [],
        measures: {
          us: {
            amount: 1.764,
            unitShort: 'oz',
            unitLong: 'ounces',
          },
          metric: {
            amount: 50.0,
            unitShort: 'g',
            unitLong: 'grams',
          },
        },
      },
      {
        id: 1012010,
        aisle: 'Spices and Seasonings',
        image: 'cinnamon.jpg',
        consistency: 'SOLID',
        name: 'ground cinnamon',
        nameClean: 'ground cinnamon',
        original: '1/2 teaspoon ground cinnamon',
        originalName: 'ground cinnamon',
        amount: 0.5,
        unit: 'teaspoon',
        meta: [],
        measures: {
          us: {
            amount: 0.5,
            unitShort: 'tsps',
            unitLong: 'teaspoons',
          },
          metric: {
            amount: 0.5,
            unitShort: 'tsps',
            unitLong: 'teaspoons',
          },
        },
      },
      {
        id: 9152,
        aisle: 'Produce',
        image: 'lemon-juice.jpg',
        consistency: 'LIQUID',
        name: 'juice of lemon',
        nameClean: 'lemon juice',
        original: 'juice of half a medium lemon',
        originalName: 'juice of half a medium lemon',
        amount: 8.0,
        unit: '',
        meta: [],
        measures: {
          us: {
            amount: 8.0,
            unitShort: '',
            unitLong: '',
          },
          metric: {
            amount: 8.0,
            unitShort: '',
            unitLong: '',
          },
        },
      },
      {
        id: 43274,
        aisle: 'Cheese',
        image: 'cream-cheese.jpg',
        consistency: 'SOLID',
        name: 'full-fat cream cheese',
        nameClean: 'reduced fat cream cheese',
        original: '225g plain, full-fat cream cheese, softened',
        originalName: 'plain, full-fat cream cheese, softened',
        amount: 225.0,
        unit: 'g',
        meta: ['plain', 'softened'],
        measures: {
          us: {
            amount: 7.937,
            unitShort: 'oz',
            unitLong: 'ounces',
          },
          metric: {
            amount: 225.0,
            unitShort: 'g',
            unitLong: 'grams',
          },
        },
      },
      {
        id: 19908,
        aisle: 'Baking',
        image: 'raw-brown-sugar.png',
        consistency: 'SOLID',
        name: 'sugar',
        nameClean: 'turbinado sugar',
        original: '50g raw sugar',
        originalName: 'raw sugar',
        amount: 50.0,
        unit: 'g',
        meta: ['raw'],
        measures: {
          us: {
            amount: 1.764,
            unitShort: 'oz',
            unitLong: 'ounces',
          },
          metric: {
            amount: 50.0,
            unitShort: 'g',
            unitLong: 'grams',
          },
        },
      },
      {
        id: 19908,
        aisle: 'Health Foods;Baking',
        image: 'raw-brown-sugar.png',
        consistency: 'SOLID',
        name: 'sugar',
        nameClean: 'turbinado sugar',
        original: '50g raw sugar',
        originalName: 'raw sugar',
        amount: 50.0,
        unit: 'g',
        meta: ['raw'],
        measures: {
          us: {
            amount: 1.764,
            unitShort: 'oz',
            unitLong: 'ounces',
          },
          metric: {
            amount: 50.0,
            unitShort: 'g',
            unitLong: 'grams',
          },
        },
      },
      {
        id: 1012047,
        aisle: 'Spices and Seasonings',
        image: 'salt.jpg',
        consistency: 'SOLID',
        name: 'sea salt',
        nameClean: 'coarse sea salt',
        original: '1 good pinch sea salt',
        originalName: 'good pinch sea salt',
        amount: 1.0,
        unit: 'pinch',
        meta: ['good'],
        measures: {
          us: {
            amount: 1.0,
            unitShort: 'pinch',
            unitLong: 'pinch',
          },
          metric: {
            amount: 1.0,
            unitShort: 'pinch',
            unitLong: 'pinch',
          },
        },
      },
      {
        id: 10019868,
        aisle: 'Baking',
        image: 'dropper.jpg',
        consistency: 'SOLID',
        name: 'sugar',
        nameClean: 'sucralose',
        original:
          "1/2 cup sugar (feel free to use Splenda Baker's Mix... I do and it is just as delicious.",
        originalName:
          "sugar (feel free to use Splenda Baker's Mix... I do and it is just as delicious",
        amount: 0.5,
        unit: 'cup',
        meta: [],
        measures: {
          us: {
            amount: 0.5,
            unitShort: 'cups',
            unitLong: 'cups',
          },
          metric: {
            amount: 100.0,
            unitShort: 'ml',
            unitLong: 'milliliters',
          },
        },
      },
      {
        id: 10019868,
        aisle: 'Baking',
        image: 'sugar-in-bowl.png',
        consistency: 'SOLID',
        name: 'sugar',
        nameClean: 'sucralose',
        original:
          "1/2 cup sugar (feel free to use Splenda Baker's Mix... I do and it is just as delicious.",
        originalName:
          "sugar (feel free to use Splenda Baker's Mix... I do and it is just as delicious",
        amount: 0.5,
        unit: 'cup',
        meta: [],
        measures: {
          us: {
            amount: 0.5,
            unitShort: 'cups',
            unitLong: 'cups',
          },
          metric: {
            amount: 100.0,
            unitShort: 'ml',
            unitLong: 'milliliters',
          },
        },
      },
      {
        id: 10019868,
        aisle: 'Baking',
        image: 'splenda.png',
        consistency: 'SOLID',
        name: 'sugar',
        nameClean: 'sucralose',
        original:
          "1/2 cup sugar (feel free to use Splenda Baker's Mix... I do and it is just as delicious.",
        originalName:
          "sugar (feel free to use Splenda Baker's Mix... I do and it is just as delicious",
        amount: 0.5,
        unit: 'cup',
        meta: [],
        measures: {
          us: {
            amount: 0.5,
            unitShort: 'cups',
            unitLong: 'cups',
          },
          metric: {
            amount: 100.0,
            unitShort: 'ml',
            unitLong: 'milliliters',
          },
        },
      },
      {
        id: 2050,
        aisle: 'Baking',
        image: 'vanilla-extract.jpg',
        consistency: 'LIQUID',
        name: 'vanilla extract',
        nameClean: 'vanilla extract',
        original: '1/2 teaspoon vanilla extract',
        originalName: 'vanilla extract',
        amount: 0.5,
        unit: 'teaspoon',
        meta: [],
        measures: {
          us: {
            amount: 0.5,
            unitShort: 'tsps',
            unitLong: 'teaspoons',
          },
          metric: {
            amount: 0.5,
            unitShort: 'tsps',
            unitLong: 'teaspoons',
          },
        },
      },
    ],
    id: 632625,
    title: 'Apple-Cheesecake Tart with Salted Caramel Glaze',
    readyInMinutes: 45,
    servings: 8,
    sourceUrl:
      'http://www.foodista.com/recipe/TQY43VQT/apple-cheesecake-tart-with-salted-caramel-glaze',
    image: 'https://spoonacular.com/recipeImages/632625-556x370.jpg',
    imageType: 'jpg',
    summary:
      'If you want to add more <b>lacto ovo vegetarian</b> recipes to your recipe box, Apple-Cheesecake Tart with Salted Caramel Glaze might be a recipe you should try. This dessert has <b>273 calories</b>, <b>6g of protein</b>, and <b>10g of fat</b> per serving. For <b>$1.55 per serving</b>, this recipe <b>covers 6%</b> of your daily requirements of vitamins and minerals. This recipe serves 8. This recipe from Foodista requires full-fat cream cheese, double cream, ground almonds, and granny smith apples. From preparation to the plate, this recipe takes roughly <b>45 minutes</b>. 40 people were glad they tried this recipe. With a spoonacular <b>score of 25%</b>, this dish is rather bad. If you like this recipe, take a look at these similar recipes: <a href="https://spoonacular.com/recipes/caramel-apple-pumpkin-spice-muffins-with-salted-caramel-glaze-612064">Caramel Apple Pumpkin Spice Muffins with Salted Caramel Glaze</a>, <a href="https://spoonacular.com/recipes/caramel-apple-pumpkin-spice-muffins-with-salted-caramel-glaze-1289101">Caramel Apple Pumpkin Spice Muffins with Salted Caramel Glaze</a>, and <a href="https://spoonacular.com/recipes/caramel-apple-pumpkin-spice-muffins-with-salted-caramel-glaze-1244543">Caramel Apple Pumpkin Spice Muffins with Salted Caramel Glaze</a>.',
    cuisines: [],
    dishTypes: ['dessert'],
    diets: ['lacto ovo vegetarian'],
    occasions: [],
    instructions:
      "<ol><li>Crust: Using a stand mixer or handheld electric whisk, cream the butter, sugar and vanilla together until lightened. By hand, gently mix in the flour and almonds. Press the resulting crumbs into a 25cm loose-bottomed tin (or several smaller ones if you have decided to make individual servings).</li><li>Custard: Using a stand mixer or handheld electric whisk, cream together the cream cheese and sugar. Add the egg and vanilla and mix to completely combine. Pour into the prepared (uncooked) crust.</li><li>Apples: Slice the apples as thinly as possible - a mandoline is good for this. Toss gently in the sugar, cinnamon and lemon. Leave to soften for 10 minutes or so. Arrange in a layer on top of the custard. Start by laying overlapping apple slices all the way round the edge. Next create the 'rose' - arrange the slices in a spiral, standing the apple slices a little on their edge, until the centre hole is completely filled in. Save the smallest, thinnest pieces for the very centre as they will have to bend the most. Cover the tart with tin foil and bake in a preheated oven set at 190c for 30 minutes (this step helps soften the apples). Remove the foil and bake for 15-25 minutes longer, until the custard is puffed and the apple edges are lightly browned.</li><li>Glaze: When you take the tin foil off the apple tart, start making the glaze. Melt the sugar in a small saucepan over medium-high heat and cook until rich and golden. Add the butter and salt and stir to combine. Add the cream and continue to cook, stirring constantly, until the ingredients have formed a smooth, unified caramel. When the tart looks nearly ready, remove it from the oven and brush with the glaze. Return to the oven and cook for a further few minutes until the glaze is gently bubbling. Cool to room temperature.  Can be kept in the fridge for several days - store in the baking tin and wrap well.</li></ol>",
    analyzedInstructions: [
      {
        name: '',
        steps: [
          {
            number: 1,
            step: 'Crust: Using a stand mixer or handheld electric whisk, cream the butter, sugar and vanilla together until lightened. By hand, gently mix in the flour and almonds. Press the resulting crumbs into a 25cm loose-bottomed tin (or several smaller ones if you have decided to make individual servings).Custard: Using a stand mixer or handheld electric whisk, cream together the cream cheese and sugar.',
            ingredients: [
              {
                id: 1017,
                name: 'cream cheese',
                localizedName: 'cream cheese',
                image: 'cream-cheese.jpg',
              },
              {
                id: 12061,
                name: 'almonds',
                localizedName: 'almonds',
                image: 'almonds.jpg',
              },
              {
                id: 19170,
                name: 'custard',
                localizedName: 'custard',
                image: 'custard.png',
              },
              {
                id: 1052050,
                name: 'vanilla',
                localizedName: 'vanilla',
                image: 'vanilla.jpg',
              },
              {
                id: 1001,
                name: 'butter',
                localizedName: 'butter',
                image: 'butter-sliced.jpg',
              },
              {
                id: 1053,
                name: 'cream',
                localizedName: 'cream',
                image: 'fluid-cream.jpg',
              },
              {
                id: 0,
                name: 'crust',
                localizedName: 'crust',
                image: '',
              },
              {
                id: 20081,
                name: 'all purpose flour',
                localizedName: 'all purpose flour',
                image: 'flour.png',
              },
              {
                id: 19335,
                name: 'sugar',
                localizedName: 'sugar',
                image: 'sugar-in-bowl.png',
              },
            ],
            equipment: [
              {
                id: 404665,
                name: 'stand mixer',
                localizedName: 'stand mixer',
                image: 'stand-mixer.jpg',
              },
              {
                id: 404661,
                name: 'whisk',
                localizedName: 'whisk',
                image: 'whisk.png',
              },
            ],
          },
          {
            number: 2,
            step: 'Add the egg and vanilla and mix to completely combine.',
            ingredients: [
              {
                id: 1052050,
                name: 'vanilla',
                localizedName: 'vanilla',
                image: 'vanilla.jpg',
              },
              {
                id: 1123,
                name: 'egg',
                localizedName: 'egg',
                image: 'egg.png',
              },
            ],
            equipment: [],
          },
          {
            number: 3,
            step: "Pour into the prepared (uncooked) crust.Apples: Slice the apples as thinly as possible - a mandoline is good for this. Toss gently in the sugar, cinnamon and lemon. Leave to soften for 10 minutes or so. Arrange in a layer on top of the custard. Start by laying overlapping apple slices all the way round the edge. Next create the 'rose' - arrange the slices in a spiral, standing the apple slices a little on their edge, until the centre hole is completely filled in. Save the smallest, thinnest pieces for the very centre as they will have to bend the most. Cover the tart with tin foil and bake in a preheated oven set at 190c for 30 minutes (this step helps soften the apples).",
            ingredients: [
              {
                id: 2010,
                name: 'cinnamon',
                localizedName: 'cinnamon',
                image: 'cinnamon.jpg',
              },
              {
                id: 19170,
                name: 'custard',
                localizedName: 'custard',
                image: 'custard.png',
              },
              {
                id: 9003,
                name: 'apple',
                localizedName: 'apple',
                image: 'apple.jpg',
              },
              {
                id: 0,
                name: 'crust',
                localizedName: 'crust',
                image: '',
              },
              {
                id: 9150,
                name: 'lemon',
                localizedName: 'lemon',
                image: 'lemon.png',
              },
              {
                id: 19335,
                name: 'sugar',
                localizedName: 'sugar',
                image: 'sugar-in-bowl.png',
              },
            ],
            equipment: [
              {
                id: 404687,
                name: 'mandoline',
                localizedName: 'mandoline',
                image: 'mandoline-slicer.png',
              },
              {
                id: 404784,
                name: 'oven',
                localizedName: 'oven',
                image: 'oven.jpg',
                temperature: {
                  number: 190.0,
                  unit: 'Celsius',
                },
              },
              {
                id: 404765,
                name: 'aluminum foil',
                localizedName: 'aluminum foil',
                image: 'aluminum-foil.png',
              },
            ],
            length: {
              number: 40,
              unit: 'minutes',
            },
          },
          {
            number: 4,
            step: 'Remove the foil and bake for 15-25 minutes longer, until the custard is puffed and the apple edges are lightly browned.Glaze: When you take the tin foil off the apple tart, start making the glaze. Melt the sugar in a small saucepan over medium-high heat and cook until rich and golden.',
            ingredients: [
              {
                id: 19170,
                name: 'custard',
                localizedName: 'custard',
                image: 'custard.png',
              },
              {
                id: 9003,
                name: 'apple',
                localizedName: 'apple',
                image: 'apple.jpg',
              },
              {
                id: 0,
                name: 'glaze',
                localizedName: 'glaze',
                image: '',
              },
              {
                id: 19335,
                name: 'sugar',
                localizedName: 'sugar',
                image: 'sugar-in-bowl.png',
              },
            ],
            equipment: [
              {
                id: 404784,
                name: 'oven',
                localizedName: 'oven',
                image: 'oven.jpg',
              },
              {
                id: 404669,
                name: 'sauce pan',
                localizedName: 'sauce pan',
                image: 'sauce-pan.jpg',
              },
              {
                id: 404765,
                name: 'aluminum foil',
                localizedName: 'aluminum foil',
                image: 'aluminum-foil.png',
              },
            ],
            length: {
              number: 25,
              unit: 'minutes',
            },
          },
          {
            number: 5,
            step: 'Add the butter and salt and stir to combine.',
            ingredients: [
              {
                id: 1001,
                name: 'butter',
                localizedName: 'butter',
                image: 'butter-sliced.jpg',
              },
              {
                id: 2047,
                name: 'salt',
                localizedName: 'salt',
                image: 'salt.jpg',
              },
            ],
            equipment: [],
          },
          {
            number: 6,
            step: 'Add the cream and continue to cook, stirring constantly, until the ingredients have formed a smooth, unified caramel. When the tart looks nearly ready, remove it from the oven and brush with the glaze. Return to the oven and cook for a further few minutes until the glaze is gently bubbling. Cool to room temperature.  Can be kept in the fridge for several days - store in the baking tin and wrap well.',
            ingredients: [
              {
                id: 19074,
                name: 'caramel',
                localizedName: 'caramel',
                image: 'soft-caramels.jpg',
              },
              {
                id: 1053,
                name: 'cream',
                localizedName: 'cream',
                image: 'fluid-cream.jpg',
              },
              {
                id: 0,
                name: 'glaze',
                localizedName: 'glaze',
                image: '',
              },
              {
                id: 10018364,
                name: 'wrap',
                localizedName: 'wrap',
                image: 'flour-tortilla.jpg',
              },
            ],
            equipment: [
              {
                id: 404784,
                name: 'oven',
                localizedName: 'oven',
                image: 'oven.jpg',
              },
            ],
          },
        ],
      },
    ],
    originalId: null,
    spoonacularSourceUrl:
      'https://spoonacular.com/apple-cheesecake-tart-with-salted-caramel-glaze-632625',
  },
  {
    vegetarian: false,
    vegan: false,
    glutenFree: true,
    dairyFree: true,
    veryHealthy: false,
    cheap: false,
    veryPopular: false,
    sustainable: false,
    lowFodmap: false,
    weightWatcherSmartPoints: 6,
    gaps: 'no',
    preparationMinutes: -1,
    cookingMinutes: -1,
    aggregateLikes: 50,
    healthScore: 4,
    creditsText: 'Foodista.com – The Cooking Encyclopedia Everyone Can Edit',
    license: 'CC BY 3.0',
    sourceName: 'Foodista',
    pricePerServing: 96.39,
    extendedIngredients: [
      {
        id: 5091,
        aisle: 'Meat',
        image: 'chicken-thigh.jpg',
        consistency: 'SOLID',
        name: 'chicken thighs',
        nameClean: 'boneless skin on chicken thighs',
        original: '1 large chicken jointed into 8-10 pieces or chicken thighs',
        originalName: 'chicken jointed into 8-10 pieces or chicken thighs',
        amount: 1.0,
        unit: 'large',
        meta: [],
        measures: {
          us: {
            amount: 1.0,
            unitShort: 'large',
            unitLong: 'large',
          },
          metric: {
            amount: 1.0,
            unitShort: 'large',
            unitLong: 'large',
          },
        },
      },
      {
        id: 5091,
        aisle: 'Meat',
        image: 'chicken-thighs.png',
        consistency: 'SOLID',
        name: 'chicken thighs',
        nameClean: 'boneless skin on chicken thighs',
        original: '1 large chicken jointed into 8-10 pieces or chicken thighs',
        originalName: 'chicken jointed into 8-10 pieces or chicken thighs',
        amount: 1.0,
        unit: 'large',
        meta: [],
        measures: {
          us: {
            amount: 1.0,
            unitShort: 'large',
            unitLong: 'large',
          },
          metric: {
            amount: 1.0,
            unitShort: 'large',
            unitLong: 'large',
          },
        },
      },
      {
        id: 5091,
        aisle: 'Meat',
        image: 'chicken-thighs.png',
        consistency: 'SOLID',
        name: 'chicken thighs',
        nameClean: 'boneless skin on chicken thighs',
        original: '1 large chicken jointed into 8-10 pieces or chicken thighs',
        originalName: 'chicken jointed into 8-10 pieces or chicken thighs',
        amount: 1.0,
        unit: 'large',
        meta: [],
        measures: {
          us: {
            amount: 1.0,
            unitShort: 'large',
            unitLong: 'large',
          },
          metric: {
            amount: 1.0,
            unitShort: 'large',
            unitLong: 'large',
          },
        },
      },
      {
        id: 1102047,
        aisle: 'Spices and Seasonings',
        image: 'salt-and-pepper.jpg',
        consistency: 'SOLID',
        name: 'sea salt and pepper',
        nameClean: 'salt and pepper',
        original: 'Sea salt and black pepper',
        originalName: 'Sea salt and black pepper',
        amount: 6.0,
        unit: 'servings',
        meta: ['black'],
        measures: {
          us: {
            amount: 6.0,
            unitShort: 'servings',
            unitLong: 'servings',
          },
          metric: {
            amount: 6.0,
            unitShort: 'servings',
            unitLong: 'servings',
          },
        },
      },
      {
        id: 4053,
        aisle: 'Oil, Vinegar, Salad Dressing',
        image: 'olive-oil.jpg',
        consistency: 'LIQUID',
        name: 'olive oil',
        nameClean: 'olive oil',
        original: '4 tablespoons olive oil',
        originalName: 'olive oil',
        amount: 4.0,
        unit: 'tablespoons',
        meta: [],
        measures: {
          us: {
            amount: 4.0,
            unitShort: 'Tbsps',
            unitLong: 'Tbsps',
          },
          metric: {
            amount: 4.0,
            unitShort: 'Tbsps',
            unitLong: 'Tbsps',
          },
        },
      },
      {
        id: 11215,
        aisle: 'Produce',
        image: 'garlic.png',
        consistency: 'SOLID',
        name: 'garlic',
        nameClean: 'garlic',
        original: '2 cloves of garlic, halved horizontally',
        originalName: 'garlic, halved horizontally',
        amount: 2.0,
        unit: 'cloves',
        meta: ['halved'],
        measures: {
          us: {
            amount: 2.0,
            unitShort: 'cloves',
            unitLong: 'cloves',
          },
          metric: {
            amount: 2.0,
            unitShort: 'cloves',
            unitLong: 'cloves',
          },
        },
      },
      {
        id: 1012049,
        aisle: 'Produce',
        image: 'thyme.jpg',
        consistency: 'SOLID',
        name: 'thyme sprigs',
        nameClean: 'fresh thyme',
        original: 'Few thyme sprigs',
        originalName: 'Few thyme sprigs',
        amount: 9.0,
        unit: 'servings',
        meta: [],
        measures: {
          us: {
            amount: 9.0,
            unitShort: 'servings',
            unitLong: 'servings',
          },
          metric: {
            amount: 9.0,
            unitShort: 'servings',
            unitLong: 'servings',
          },
        },
      },
      {
        id: 1022068,
        aisle: 'Oil, Vinegar, Salad Dressing',
        image: 'red-wine-vinegar.jpg',
        consistency: 'LIQUID',
        name: 'splash of red wine vinegar',
        nameClean: 'red wine vinegar',
        original: 'Splash of red wine vinegar',
        originalName: 'Splash of red wine vinegar',
        amount: 6.0,
        unit: 'servings',
        meta: [],
        measures: {
          us: {
            amount: 6.0,
            unitShort: 'servings',
            unitLong: 'servings',
          },
          metric: {
            amount: 6.0,
            unitShort: 'servings',
            unitLong: 'servings',
          },
        },
      },
      {
        id: 16124,
        aisle: 'Ethnic Foods;Condiments',
        image: 'soy-sauce.jpg',
        consistency: 'LIQUID',
        name: 'soy sauce',
        nameClean: 'soy sauce',
        original: '2 tablespoons dark soy sauce',
        originalName: 'dark soy sauce',
        amount: 2.0,
        unit: 'tablespoons',
        meta: ['dark'],
        measures: {
          us: {
            amount: 2.0,
            unitShort: 'Tbsps',
            unitLong: 'Tbsps',
          },
          metric: {
            amount: 2.0,
            unitShort: 'Tbsps',
            unitLong: 'Tbsps',
          },
        },
      },
      {
        id: 19296,
        aisle: 'Nut butters, Jams, and Honey',
        image: 'honey.png',
        consistency: 'LIQUID',
        name: 'honey',
        nameClean: 'honey',
        original: '3 tablespoons honey',
        originalName: 'honey',
        amount: 3.0,
        unit: 'tablespoons',
        meta: [],
        measures: {
          us: {
            amount: 3.0,
            unitShort: 'Tbsps',
            unitLong: 'Tbsps',
          },
          metric: {
            amount: 3.0,
            unitShort: 'Tbsps',
            unitLong: 'Tbsps',
          },
        },
      },
      {
        id: 9150,
        aisle: 'Produce',
        image: 'lemon.png',
        consistency: 'SOLID',
        name: 'lemon',
        nameClean: 'lemon',
        original: '1 lemon, finely sliced',
        originalName: 'lemon, finely sliced',
        amount: 1.0,
        unit: '',
        meta: ['finely sliced'],
        measures: {
          us: {
            amount: 1.0,
            unitShort: '',
            unitLong: '',
          },
          metric: {
            amount: 1.0,
            unitShort: '',
            unitLong: '',
          },
        },
      },
      {
        id: 10311297,
        aisle: 'Produce',
        image: 'parsley.jpg',
        consistency: 'SOLID',
        name: 'flat leaf parsley',
        nameClean: 'flat leaf parsley',
        original: 'Bunch of flat leaf parsley, chopped',
        originalName: 'flat leaf parsley, chopped',
        amount: 1.0,
        unit: 'Bunch',
        meta: ['chopped'],
        measures: {
          us: {
            amount: 1.0,
            unitShort: 'Bunch',
            unitLong: 'Bunch',
          },
          metric: {
            amount: 1.0,
            unitShort: 'Bunch',
            unitLong: 'Bunch',
          },
        },
      },
    ],
    id: 649503,
    title: 'Lemon and Honey Chicken',
    readyInMinutes: 45,
    servings: 6,
    sourceUrl:
      'https://www.foodista.com/recipe/PQH3HGJL/lemon-and-honey-chicken',
    image: 'https://spoonacular.com/recipeImages/649503-556x370.jpg',
    imageType: 'jpg',
    summary:
      'Need a <b>gluten free and dairy free side dish</b>? Lemon and Honey Chicken could be a spectacular recipe to try. One portion of this dish contains around <b>4g of protein</b>, <b>13g of fat</b>, and a total of <b>172 calories</b>. For <b>96 cents per serving</b>, this recipe <b>covers 10%</b> of your daily requirements of vitamins and minerals. This recipe serves 6. 50 people found this recipe to be yummy and satisfying. A mixture of splash of red wine vinegar, garlic, lemon, and a handful of other ingredients are all it takes to make this recipe so delicious. It is brought to you by Foodista. From preparation to the plate, this recipe takes roughly <b>45 minutes</b>. All things considered, we decided this recipe <b>deserves a spoonacular score of 42%</b>. This score is pretty good. If you like this recipe, take a look at these similar recipes: <a href="https://spoonacular.com/recipes/honey-lemon-chicken-1471533">Honey Lemon Chicken</a>, <a href="https://spoonacular.com/recipes/honey-lemon-chicken-415127">Honey Lemon Chicken</a>, and <a href="https://spoonacular.com/recipes/honey-lemon-chicken-142979">Honey Lemon Chicken</a>.',
    cuisines: [],
    dishTypes: ['side dish'],
    diets: ['gluten free', 'dairy free'],
    occasions: [],
    instructions:
      'Cooking Method:\nSeason the chicken with salt and pepper and heat the olive oil in a large saut pan. Brown the chicken pieces (in batches if necessary) over a high heat with the garlic and thyme for 23 minutes on each side until golden brown. Return all the chicken to the pan, add the vinegar and bubble until reduced by half. Drizzle over the soy sauce and honey and shake the pan to mix.\nPour in a 1/2 cup of hot water and add the lemon slices. Let the liquid bubble and reduce down until syrupy, which will take about 10 minutes or so. By now the chicken should be cooked through.\nTransfer the chicken to a platter and sprinkle over the chopped parsley.\nServe with mashed potato (boil potatoes, add milk and butter and mash together, add cooked peas and carrots and some thyme).',
    analyzedInstructions: [
      {
        name: 'Cooking Method',
        steps: [
          {
            number: 1,
            step: 'Season the chicken with salt and pepper and heat the olive oil in a large saut pan. Brown the chicken pieces (in batches if necessary) over a high heat with the garlic and thyme for 23 minutes on each side until golden brown. Return all the chicken to the pan, add the vinegar and bubble until reduced by half.',
            ingredients: [
              {
                id: 1102047,
                name: 'salt and pepper',
                localizedName: 'salt and pepper',
                image: 'salt-and-pepper.jpg',
              },
              {
                id: 1005006,
                name: 'chicken pieces',
                localizedName: 'chicken pieces',
                image: 'chicken-parts.jpg',
              },
              {
                id: 4053,
                name: 'olive oil',
                localizedName: 'olive oil',
                image: 'olive-oil.jpg',
              },
              {
                id: 5006,
                name: 'whole chicken',
                localizedName: 'whole chicken',
                image: 'whole-chicken.jpg',
              },
              {
                id: 2053,
                name: 'vinegar',
                localizedName: 'vinegar',
                image: 'vinegar-(white).jpg',
              },
              {
                id: 11215,
                name: 'garlic',
                localizedName: 'garlic',
                image: 'garlic.png',
              },
              {
                id: 2049,
                name: 'thyme',
                localizedName: 'thyme',
                image: 'thyme.jpg',
              },
            ],
            equipment: [
              {
                id: 404645,
                name: 'frying pan',
                localizedName: 'frying pan',
                image: 'pan.png',
              },
            ],
            length: {
              number: 23,
              unit: 'minutes',
            },
          },
          {
            number: 2,
            step: 'Drizzle over the soy sauce and honey and shake the pan to mix.',
            ingredients: [
              {
                id: 16124,
                name: 'soy sauce',
                localizedName: 'soy sauce',
                image: 'soy-sauce.jpg',
              },
              {
                id: 19296,
                name: 'honey',
                localizedName: 'honey',
                image: 'honey.png',
              },
              {
                id: 0,
                name: 'shake',
                localizedName: 'shake',
                image: '',
              },
            ],
            equipment: [
              {
                id: 404645,
                name: 'frying pan',
                localizedName: 'frying pan',
                image: 'pan.png',
              },
            ],
          },
          {
            number: 3,
            step: 'Pour in a 1/2 cup of hot water and add the lemon slices.',
            ingredients: [
              {
                id: 9150,
                name: 'lemon',
                localizedName: 'lemon',
                image: 'lemon.png',
              },
              {
                id: 14412,
                name: 'water',
                localizedName: 'water',
                image: 'water.png',
              },
            ],
            equipment: [],
          },
          {
            number: 4,
            step: 'Let the liquid bubble and reduce down until syrupy, which will take about 10 minutes or so. By now the chicken should be cooked through.',
            ingredients: [
              {
                id: 5006,
                name: 'whole chicken',
                localizedName: 'whole chicken',
                image: 'whole-chicken.jpg',
              },
            ],
            equipment: [],
            length: {
              number: 10,
              unit: 'minutes',
            },
          },
          {
            number: 5,
            step: 'Transfer the chicken to a platter and sprinkle over the chopped parsley.',
            ingredients: [
              {
                id: 5006,
                name: 'whole chicken',
                localizedName: 'whole chicken',
                image: 'whole-chicken.jpg',
              },
              {
                id: 11297,
                name: 'parsley',
                localizedName: 'parsley',
                image: 'parsley.jpg',
              },
            ],
            equipment: [],
          },
          {
            number: 6,
            step: 'Serve with mashed potato (boil potatoes, add milk and butter and mash together, add cooked peas and carrots and some thyme).',
            ingredients: [
              {
                id: 11322,
                name: 'peas and carrots',
                localizedName: 'peas and carrots',
                image: 'peas-and-carrots.jpg',
              },
              {
                id: 11352,
                name: 'potato',
                localizedName: 'potato',
                image: 'potatoes-yukon-gold.png',
              },
              {
                id: 1001,
                name: 'butter',
                localizedName: 'butter',
                image: 'butter-sliced.jpg',
              },
              {
                id: 2049,
                name: 'thyme',
                localizedName: 'thyme',
                image: 'thyme.jpg',
              },
              {
                id: 1077,
                name: 'milk',
                localizedName: 'milk',
                image: 'milk.png',
              },
            ],
            equipment: [],
          },
        ],
      },
    ],
    originalId: null,
    spoonacularSourceUrl:
      'https://spoonacular.com/lemon-and-honey-chicken-649503',
  },
  {
    vegetarian: true,
    vegan: false,
    glutenFree: false,
    dairyFree: true,
    veryHealthy: false,
    cheap: false,
    veryPopular: false,
    sustainable: false,
    lowFodmap: false,
    weightWatcherSmartPoints: 8,
    gaps: 'no',
    preparationMinutes: -1,
    cookingMinutes: -1,
    aggregateLikes: 4,
    healthScore: 49,
    creditsText: 'Foodista.com – The Cooking Encyclopedia Everyone Can Edit',
    license: 'CC BY 3.0',
    sourceName: 'Foodista',
    pricePerServing: 229.92,
    extendedIngredients: [
      {
        id: 1123,
        aisle: 'Milk, Eggs, Other Dairy',
        image: 'egg.png',
        consistency: 'SOLID',
        name: 'high-omega three eggs',
        nameClean: 'egg',
        original: '2 high-omega three eggs',
        originalName: 'high-omega three eggs',
        amount: 2.0,
        unit: '',
        meta: [],
        measures: {
          us: {
            amount: 2.0,
            unitShort: '',
            unitLong: '',
          },
          metric: {
            amount: 2.0,
            unitShort: '',
            unitLong: '',
          },
        },
      },
      {
        id: 2053,
        aisle: 'Oil, Vinegar, Salad Dressing',
        image: 'vinegar-(white).jpg',
        consistency: 'LIQUID',
        name: 'vinegar',
        nameClean: 'distilled white vinegar',
        original: '1 tablespoon white vinegar',
        originalName: 'white vinegar',
        amount: 1.0,
        unit: 'tablespoon',
        meta: ['white'],
        measures: {
          us: {
            amount: 1.0,
            unitShort: 'Tbsp',
            unitLong: 'Tbsp',
          },
          metric: {
            amount: 1.0,
            unitShort: 'Tbsp',
            unitLong: 'Tbsp',
          },
        },
      },
      {
        id: 4053,
        aisle: 'Oil, Vinegar, Salad Dressing',
        image: 'olive-oil.jpg',
        consistency: 'LIQUID',
        name: 'olive oil',
        nameClean: 'olive oil',
        original: 'olive oil',
        originalName: 'olive oil',
        amount: 2.0,
        unit: 'servings',
        meta: [],
        measures: {
          us: {
            amount: 2.0,
            unitShort: 'servings',
            unitLong: 'servings',
          },
          metric: {
            amount: 2.0,
            unitShort: 'servings',
            unitLong: 'servings',
          },
        },
      },
      {
        id: 11215,
        aisle: 'Produce',
        image: 'garlic.png',
        consistency: 'SOLID',
        name: 'garlic',
        nameClean: 'garlic',
        original: '2 cloves of garlic, sliced finely',
        originalName: 'garlic, sliced finely',
        amount: 2.0,
        unit: 'cloves',
        meta: ['sliced', 'finely'],
        measures: {
          us: {
            amount: 2.0,
            unitShort: 'cloves',
            unitLong: 'cloves',
          },
          metric: {
            amount: 2.0,
            unitShort: 'cloves',
            unitLong: 'cloves',
          },
        },
      },
      {
        id: 1032009,
        aisle: 'Spices and Seasonings',
        image: 'red-pepper-flakes.jpg',
        consistency: 'SOLID',
        name: 'chilli flakes',
        nameClean: 'red pepper flakes',
        original: 'pinch of dried chilli flakes',
        originalName: 'pinch of dried chilli flakes',
        amount: 1.0,
        unit: 'pinch',
        meta: ['dried'],
        measures: {
          us: {
            amount: 1.0,
            unitShort: 'pinch',
            unitLong: 'pinch',
          },
          metric: {
            amount: 1.0,
            unitShort: 'pinch',
            unitLong: 'pinch',
          },
        },
      },
      {
        id: 10011457,
        aisle: 'Produce',
        image: 'spinach.jpg',
        consistency: 'SOLID',
        name: 'spinach leaves',
        nameClean: 'spinach',
        original: '1 bunch fresh spinach leaves, chopped roughly',
        originalName: 'fresh spinach leaves, chopped roughly',
        amount: 1.0,
        unit: 'bunch',
        meta: ['fresh', 'chopped'],
        measures: {
          us: {
            amount: 1.0,
            unitShort: 'bunch',
            unitLong: 'bunch',
          },
          metric: {
            amount: 1.0,
            unitShort: 'bunch',
            unitLong: 'bunch',
          },
        },
      },
      {
        id: 1102047,
        aisle: 'Spices and Seasonings',
        image: 'salt-and-pepper.jpg',
        consistency: 'SOLID',
        name: 'salt and pepper',
        nameClean: 'salt and pepper',
        original: 'salt and pepper to taste',
        originalName: 'salt and pepper to taste',
        amount: 2.0,
        unit: 'servings',
        meta: ['to taste'],
        measures: {
          us: {
            amount: 2.0,
            unitShort: 'servings',
            unitLong: 'servings',
          },
          metric: {
            amount: 2.0,
            unitShort: 'servings',
            unitLong: 'servings',
          },
        },
      },
      {
        id: 18075,
        aisle: 'Bakery/Bread',
        image: 'multigrain-bread.png',
        consistency: 'SOLID',
        name: 'grain bread',
        nameClean: 'whole wheat bread',
        original: '2 slices whole grain bread, toasted',
        originalName: 'whole grain bread, toasted',
        amount: 2.0,
        unit: 'slices',
        meta: ['whole', 'toasted'],
        measures: {
          us: {
            amount: 2.0,
            unitShort: 'slice',
            unitLong: 'slices',
          },
          metric: {
            amount: 2.0,
            unitShort: 'slice',
            unitLong: 'slices',
          },
        },
      },
      {
        id: 18075,
        aisle: 'Bakery/Bread',
        image: 'whole-wheat-bread.jpg',
        consistency: 'SOLID',
        name: 'grain bread',
        nameClean: 'whole wheat bread',
        original: '2 slices whole grain bread, toasted',
        originalName: 'whole grain bread, toasted',
        amount: 2.0,
        unit: 'slices',
        meta: ['whole', 'toasted'],
        measures: {
          us: {
            amount: 2.0,
            unitShort: 'slice',
            unitLong: 'slices',
          },
          metric: {
            amount: 2.0,
            unitShort: 'slice',
            unitLong: 'slices',
          },
        },
      },
      {
        id: 11529,
        aisle: 'Produce',
        image: 'tomato.png',
        consistency: 'SOLID',
        name: 'tomato',
        nameClean: 'tomato',
        original: '1 tomato, sliced finely into rounds',
        originalName: 'tomato, sliced finely into rounds',
        amount: 1.0,
        unit: '',
        meta: ['sliced', 'finely'],
        measures: {
          us: {
            amount: 1.0,
            unitShort: '',
            unitLong: '',
          },
          metric: {
            amount: 1.0,
            unitShort: '',
            unitLong: '',
          },
        },
      },
    ],
    id: 656481,
    title: 'Poached Egg With Spinach and Tomato',
    readyInMinutes: 45,
    servings: 2,
    sourceUrl:
      'https://www.foodista.com/recipe/YYK36BYD/poached-egg-with-spinach-and-tomato',
    image: 'https://spoonacular.com/recipeImages/656481-556x370.jpg',
    imageType: 'jpg',
    summary:
      'Poached Egg With Spinach and Tomato is a breakfast that serves 2. One serving contains <b>314 calories</b>, <b>15g of protein</b>, and <b>20g of fat</b>. For <b>$2.3 per serving</b>, this recipe <b>covers 36%</b> of your daily requirements of vitamins and minerals. A mixture of high-omega three eggs, grain bread, olive oil, and a handful of other ingredients are all it takes to make this recipe so scrumptious. It is brought to you by Foodista. 4 people have tried and liked this recipe. It is a good option if you\'re following a <b>dairy free and lacto ovo vegetarian</b> diet. From preparation to the plate, this recipe takes roughly <b>45 minutes</b>. Overall, this recipe earns a <b>spectacular spoonacular score of 87%</b>. If you like this recipe, take a look at these similar recipes: <a href="https://spoonacular.com/recipes/poached-egg-with-spinach-and-tomato-1406883">Poached Egg With Spinach and Tomato</a>, <a href="https://spoonacular.com/recipes/poached-egg-with-sauteed-spinach-for-two-19781">Poached Egg With Sauteed Spinach For Two</a>, and <a href="https://spoonacular.com/recipes/quinoa-with-poached-egg-spinach-and-cucumber-22940">Quinoa With Poached Egg, Spinach, And Cucumber</a>.',
    cuisines: [],
    dishTypes: ['morning meal', 'brunch', 'breakfast'],
    diets: ['dairy free', 'lacto ovo vegetarian'],
    occasions: [],
    instructions:
      "Take a wide skillet and fill it with enough water so the eggs can be submerged. Bring it up to a steady boil and then drop the temperature so it's at a steady simmer. Add the vinegar.\nBreak one egg into a bowl and slowly pour into the boiling water. Do the same with the second egg. Let it cook until the white is cooked around the yolk, about two to three minutes.\nIn the meanwhile, heat another wide frying pan and add some olive oil. Add the garlic and chilli and saut for about a minute until fragrant. Add the spinach, mix gently and cover. Cook for a minute and shut off the heat. Season to taste with salt and pepper. Separate amidst the two slices of toast and add some slices of tomato.\nTop each bed of vegetables with a poached egg. Season with some salt and pepper. Serve immediately.",
    analyzedInstructions: [
      {
        name: '',
        steps: [
          {
            number: 1,
            step: "Take a wide skillet and fill it with enough water so the eggs can be submerged. Bring it up to a steady boil and then drop the temperature so it's at a steady simmer.",
            ingredients: [
              {
                id: 14412,
                name: 'water',
                localizedName: 'water',
                image: 'water.png',
              },
              {
                id: 1123,
                name: 'egg',
                localizedName: 'egg',
                image: 'egg.png',
              },
            ],
            equipment: [
              {
                id: 404645,
                name: 'frying pan',
                localizedName: 'frying pan',
                image: 'pan.png',
              },
            ],
          },
          {
            number: 2,
            step: 'Add the vinegar.',
            ingredients: [
              {
                id: 2053,
                name: 'vinegar',
                localizedName: 'vinegar',
                image: 'vinegar-(white).jpg',
              },
            ],
            equipment: [],
          },
          {
            number: 3,
            step: 'Break one egg into a bowl and slowly pour into the boiling water. Do the same with the second egg.',
            ingredients: [
              {
                id: 14412,
                name: 'water',
                localizedName: 'water',
                image: 'water.png',
              },
              {
                id: 1123,
                name: 'egg',
                localizedName: 'egg',
                image: 'egg.png',
              },
            ],
            equipment: [
              {
                id: 404783,
                name: 'bowl',
                localizedName: 'bowl',
                image: 'bowl.jpg',
              },
            ],
          },
          {
            number: 4,
            step: 'Let it cook until the white is cooked around the yolk, about two to three minutes.',
            ingredients: [
              {
                id: 1125,
                name: 'egg yolk',
                localizedName: 'egg yolk',
                image: 'egg-yolk.jpg',
              },
            ],
            equipment: [],
            length: {
              number: 2,
              unit: 'minutes',
            },
          },
          {
            number: 5,
            step: 'In the meanwhile, heat another wide frying pan and add some olive oil.',
            ingredients: [
              {
                id: 4053,
                name: 'olive oil',
                localizedName: 'olive oil',
                image: 'olive-oil.jpg',
              },
            ],
            equipment: [
              {
                id: 404645,
                name: 'frying pan',
                localizedName: 'frying pan',
                image: 'pan.png',
              },
            ],
          },
          {
            number: 6,
            step: 'Add the garlic and chilli and saut for about a minute until fragrant.',
            ingredients: [
              {
                id: 11819,
                name: 'chili pepper',
                localizedName: 'chili pepper',
                image: 'red-chili.jpg',
              },
              {
                id: 11215,
                name: 'garlic',
                localizedName: 'garlic',
                image: 'garlic.png',
              },
            ],
            equipment: [],
          },
          {
            number: 7,
            step: 'Add the spinach, mix gently and cover. Cook for a minute and shut off the heat. Season to taste with salt and pepper. Separate amidst the two slices of toast and add some slices of tomato.',
            ingredients: [
              {
                id: 1102047,
                name: 'salt and pepper',
                localizedName: 'salt and pepper',
                image: 'salt-and-pepper.jpg',
              },
              {
                id: 10011457,
                name: 'spinach',
                localizedName: 'spinach',
                image: 'spinach.jpg',
              },
              {
                id: 11529,
                name: 'tomato',
                localizedName: 'tomato',
                image: 'tomato.png',
              },
              {
                id: 0,
                name: 'sandwich bread',
                localizedName: 'sandwich bread',
                image: 'white-bread.jpg',
              },
            ],
            equipment: [],
          },
          {
            number: 8,
            step: 'Top each bed of vegetables with a poached egg. Season with some salt and pepper.',
            ingredients: [
              {
                id: 1102047,
                name: 'salt and pepper',
                localizedName: 'salt and pepper',
                image: 'salt-and-pepper.jpg',
              },
              {
                id: 1131,
                name: 'poached egg',
                localizedName: 'poached egg',
                image: 'poached-egg.png',
              },
              {
                id: 11583,
                name: 'vegetable',
                localizedName: 'vegetable',
                image: 'mixed-vegetables.png',
              },
            ],
            equipment: [],
          },
          {
            number: 9,
            step: 'Serve immediately.',
            ingredients: [],
            equipment: [],
          },
        ],
      },
    ],
    originalId: null,
    spoonacularSourceUrl:
      'https://spoonacular.com/poached-egg-with-spinach-and-tomato-656481',
  },
  {
    vegetarian: false,
    vegan: false,
    glutenFree: false,
    dairyFree: true,
    veryHealthy: false,
    cheap: false,
    veryPopular: false,
    sustainable: false,
    lowFodmap: false,
    weightWatcherSmartPoints: 6,
    gaps: 'no',
    preparationMinutes: -1,
    cookingMinutes: -1,
    aggregateLikes: 4,
    healthScore: 22,
    creditsText: 'foodista.com',
    sourceName: 'foodista.com',
    pricePerServing: 301.78,
    extendedIngredients: [
      {
        id: 15076,
        aisle: 'Seafood',
        image: 'salmon.png',
        consistency: 'SOLID',
        name: 'pink salmon',
        nameClean: 'salmon',
        original: '16 oz pink salmon',
        originalName: 'pink salmon',
        amount: 16.0,
        unit: 'oz',
        meta: [],
        measures: {
          us: {
            amount: 16.0,
            unitShort: 'oz',
            unitLong: 'ounces',
          },
          metric: {
            amount: 453.592,
            unitShort: 'g',
            unitLong: 'grams',
          },
        },
      },
      {
        id: 1123,
        aisle: 'Milk, Eggs, Other Dairy',
        image: 'egg.png',
        consistency: 'SOLID',
        name: 'eggs',
        nameClean: 'egg',
        original: '2 eggs',
        originalName: 'eggs',
        amount: 2.0,
        unit: '',
        meta: [],
        measures: {
          us: {
            amount: 2.0,
            unitShort: '',
            unitLong: '',
          },
          metric: {
            amount: 2.0,
            unitShort: '',
            unitLong: '',
          },
        },
      },
      {
        id: 2029,
        aisle: 'Spices and Seasonings',
        image: 'dried-parsley.png',
        consistency: 'SOLID',
        name: 'parsley flakes',
        nameClean: 'dried parsley',
        original: '1/4 cup fresh or dried parsley flakes',
        originalName: 'fresh or dried parsley flakes',
        amount: 0.25,
        unit: 'cup',
        meta: ['fresh'],
        measures: {
          us: {
            amount: 0.25,
            unitShort: 'cups',
            unitLong: 'cups',
          },
          metric: {
            amount: 6.25,
            unitShort: 'g',
            unitLong: 'grams',
          },
        },
      },
      {
        id: 11291,
        aisle: 'Produce',
        image: 'spring-onions.jpg',
        consistency: 'SOLID',
        name: 'scallions',
        nameClean: 'spring onions',
        original: '2 tbsp scallions',
        originalName: 'scallions',
        amount: 2.0,
        unit: 'tbsp',
        meta: [],
        measures: {
          us: {
            amount: 2.0,
            unitShort: 'Tbsps',
            unitLong: 'Tbsps',
          },
          metric: {
            amount: 2.0,
            unitShort: 'Tbsps',
            unitLong: 'Tbsps',
          },
        },
      },
      {
        id: 10028033,
        aisle: 'Bakery/Bread',
        image: 'italian-bread.jpg',
        consistency: 'SOLID',
        name: 'bread crumbs',
        nameClean: 'italian bread',
        original: '1/4 cup italian bread crumbs',
        originalName: 'italian bread crumbs',
        amount: 0.25,
        unit: 'cup',
        meta: ['italian'],
        measures: {
          us: {
            amount: 0.25,
            unitShort: 'cups',
            unitLong: 'cups',
          },
          metric: {
            amount: 7.0,
            unitShort: 'g',
            unitLong: 'grams',
          },
        },
      },
      {
        id: 9152,
        aisle: 'Produce',
        image: 'lemon-juice.jpg',
        consistency: 'LIQUID',
        name: 'juice of lemon',
        nameClean: 'lemon juice',
        original: 'Juice from 1/2 of lemon',
        originalName: 'Juice from lemon',
        amount: 0.5,
        unit: '',
        meta: [],
        measures: {
          us: {
            amount: 0.5,
            unitShort: '',
            unitLong: '',
          },
          metric: {
            amount: 0.5,
            unitShort: '',
            unitLong: '',
          },
        },
      },
      {
        id: 1032009,
        aisle: 'Spices and Seasonings',
        image: 'red-pepper-flakes.jpg',
        consistency: 'SOLID',
        name: 'pepper flakes',
        nameClean: 'red pepper flakes',
        original: 'Red pepper flakes to taste',
        originalName: 'Red pepper flakes to taste',
        amount: 4.0,
        unit: 'servings',
        meta: ['red', 'to taste'],
        measures: {
          us: {
            amount: 4.0,
            unitShort: 'servings',
            unitLong: 'servings',
          },
          metric: {
            amount: 4.0,
            unitShort: 'servings',
            unitLong: 'servings',
          },
        },
      },
      {
        id: 4025,
        aisle: 'Condiments',
        image: 'mayonnaise.png',
        consistency: 'LIQUID',
        name: 'mayonnaise',
        nameClean: 'mayonnaise',
        original: '2 tbsp mayonnaise',
        originalName: 'mayonnaise',
        amount: 2.0,
        unit: 'tbsp',
        meta: [],
        measures: {
          us: {
            amount: 2.0,
            unitShort: 'Tbsps',
            unitLong: 'Tbsps',
          },
          metric: {
            amount: 2.0,
            unitShort: 'Tbsps',
            unitLong: 'Tbsps',
          },
        },
      },
      {
        id: 9152,
        aisle: 'Produce',
        image: 'lemon-juice.jpg',
        consistency: 'LIQUID',
        name: 'lemon juice',
        nameClean: 'lemon juice',
        original: '1 tbsp lemon juice',
        originalName: 'lemon juice',
        amount: 1.0,
        unit: 'tbsp',
        meta: [],
        measures: {
          us: {
            amount: 1.0,
            unitShort: 'Tbsp',
            unitLong: 'Tbsp',
          },
          metric: {
            amount: 1.0,
            unitShort: 'Tbsp',
            unitLong: 'Tbsp',
          },
        },
      },
    ],
    id: 661186,
    title: 'Spicy Salmon Patties',
    readyInMinutes: 45,
    servings: 4,
    sourceUrl: 'https://www.foodista.com/recipe/VRGPZNK4/spicy-salmon-patties',
    image: 'https://spoonacular.com/recipeImages/661186-556x370.jpg',
    imageType: 'jpg',
    summary:
      'Spicy Salmon Patties takes about <b>45 minutes</b> from beginning to end. This recipe serves 4 and costs $3.02 per serving. This main course has <b>262 calories</b>, <b>26g of protein</b>, and <b>15g of fat</b> per serving. A mixture of bread crumbs, eggs, scallions, and a handful of other ingredients are all it takes to make this recipe so scrumptious. 4 people were impressed by this recipe. It is brought to you by Foodista. It is a good option if you\'re following a <b>dairy free and pescatarian</b> diet. All things considered, we decided this recipe <b>deserves a spoonacular score of 67%</b>. This score is good. Try <a href="https://spoonacular.com/recipes/spicy-salmon-patties-369195">Spicy Salmon Patties</a>, <a href="https://spoonacular.com/recipes/baked-salmon-patties-with-a-spicy-dip-612060">Baked Salmon Patties with a Spicy Dip</a>, and <a href="https://spoonacular.com/recipes/salmon-patties-with-spicy-low-fat-mayonnaise-82903">Salmon Patties With Spicy Low-fat Mayonnaise</a> for similar recipes.',
    cuisines: [],
    dishTypes: ['lunch', 'main course', 'main dish', 'dinner'],
    diets: ['dairy free', 'pescatarian'],
    occasions: [],
    instructions:
      'Prep salmon: remove skin; crush bones with thumb and index finger leaving them in for added calcium.\nKnead together salmon with eggs, parsley, scallions, bread crumbs, lemon juice and red pepper flakes.\nCook in a lightly-oiled cast-iron pan over medium heat until golden brown. Serve warm, with sauce.',
    analyzedInstructions: [
      {
        name: '',
        steps: [
          {
            number: 1,
            step: 'Prep salmon: remove skin; crush bones with thumb and index finger leaving them in for added calcium.',
            ingredients: [
              {
                id: 15076,
                name: 'salmon',
                localizedName: 'salmon',
                image: 'salmon.png',
              },
            ],
            equipment: [],
          },
          {
            number: 2,
            step: 'Knead together salmon with eggs, parsley, scallions, bread crumbs, lemon juice and red pepper flakes.',
            ingredients: [
              {
                id: 1032009,
                name: 'red pepper flakes',
                localizedName: 'red pepper flakes',
                image: 'red-pepper-flakes.jpg',
              },
              {
                id: 18079,
                name: 'breadcrumbs',
                localizedName: 'breadcrumbs',
                image: 'breadcrumbs.jpg',
              },
              {
                id: 9152,
                name: 'lemon juice',
                localizedName: 'lemon juice',
                image: 'lemon-juice.jpg',
              },
              {
                id: 11291,
                name: 'green onions',
                localizedName: 'green onions',
                image: 'spring-onions.jpg',
              },
              {
                id: 11297,
                name: 'parsley',
                localizedName: 'parsley',
                image: 'parsley.jpg',
              },
              {
                id: 15076,
                name: 'salmon',
                localizedName: 'salmon',
                image: 'salmon.png',
              },
              {
                id: 1123,
                name: 'egg',
                localizedName: 'egg',
                image: 'egg.png',
              },
            ],
            equipment: [],
          },
          {
            number: 3,
            step: 'Cook in a lightly-oiled cast-iron pan over medium heat until golden brown.',
            ingredients: [],
            equipment: [
              {
                id: 404645,
                name: 'frying pan',
                localizedName: 'frying pan',
                image: 'pan.png',
              },
            ],
          },
          {
            number: 4,
            step: 'Serve warm, with sauce.',
            ingredients: [
              {
                id: 0,
                name: 'sauce',
                localizedName: 'sauce',
                image: '',
              },
            ],
            equipment: [],
          },
        ],
      },
    ],
    originalId: null,
    spoonacularSourceUrl: 'https://spoonacular.com/spicy-salmon-patties-661186',
  },
  {
    vegetarian: true,
    vegan: false,
    glutenFree: false,
    dairyFree: false,
    veryHealthy: false,
    cheap: false,
    veryPopular: false,
    sustainable: false,
    lowFodmap: false,
    weightWatcherSmartPoints: 10,
    gaps: 'no',
    preparationMinutes: -1,
    cookingMinutes: -1,
    aggregateLikes: 5,
    healthScore: 1,
    creditsText: 'Foodista.com – The Cooking Encyclopedia Everyone Can Edit',
    license: 'CC BY 3.0',
    sourceName: 'Foodista',
    pricePerServing: 71.29,
    extendedIngredients: [
      {
        id: 20129,
        aisle: 'Baking',
        image: 'flour.png',
        consistency: 'SOLID',
        name: 'self raising flour',
        nameClean: 'self rising flour',
        original: '40g (1/4 cup) Self raising flour',
        originalName: '40g Self raising flour',
        amount: 0.25,
        unit: 'cup',
        meta: [],
        measures: {
          us: {
            amount: 0.25,
            unitShort: 'cups',
            unitLong: 'cups',
          },
          metric: {
            amount: 31.25,
            unitShort: 'g',
            unitLong: 'grams',
          },
        },
      },
      {
        id: 19335,
        aisle: 'Baking',
        image: 'sugar-in-bowl.png',
        consistency: 'SOLID',
        name: 'caster sugar',
        nameClean: 'sugar',
        original: '65g (1/3 cup) Caster sugar (reduced to 50g)',
        originalName: '65g Caster sugar (reduced to 50g)',
        amount: 0.33333334,
        unit: 'cup',
        meta: ['(reduced to 50g)'],
        measures: {
          us: {
            amount: 0.33333334,
            unitShort: 'cups',
            unitLong: 'cups',
          },
          metric: {
            amount: 66.667,
            unitShort: 'g',
            unitLong: 'grams',
          },
        },
      },
      {
        id: 1001,
        aisle: 'Milk, Eggs, Other Dairy',
        image: 'butter-sliced.jpg',
        consistency: 'SOLID',
        name: 'butter',
        nameClean: 'butter',
        original: '40g Butter, melted',
        originalName: 'Butter, melted',
        amount: 40.0,
        unit: 'g',
        meta: ['melted'],
        measures: {
          us: {
            amount: 1.411,
            unitShort: 'oz',
            unitLong: 'ounces',
          },
          metric: {
            amount: 40.0,
            unitShort: 'g',
            unitLong: 'grams',
          },
        },
      },
      {
        id: 9156,
        aisle: 'Produce',
        image: 'zest-lemon.jpg',
        consistency: 'SOLID',
        name: 'lemon zest',
        nameClean: 'lemon peel',
        original: 'Zest of 2 lemon (I only used one large lemon)',
        originalName: 'Zest of lemon (I only used one large lemon)',
        amount: 2.0,
        unit: '',
        meta: ['(I only used one large lemon)'],
        measures: {
          us: {
            amount: 2.0,
            unitShort: '',
            unitLong: '',
          },
          metric: {
            amount: 2.0,
            unitShort: '',
            unitLong: '',
          },
        },
      },
      {
        id: 9152,
        aisle: 'Produce',
        image: 'lemon-juice.jpg',
        consistency: 'LIQUID',
        name: 'lemon juice',
        nameClean: 'lemon juice',
        original: '40ml Lemon juice',
        originalName: 'Lemon juice',
        amount: 40.0,
        unit: 'ml',
        meta: [],
        measures: {
          us: {
            amount: 1.395,
            unitShort: 'fl. oz',
            unitLong: 'fl. ozs',
          },
          metric: {
            amount: 40.0,
            unitShort: 'ml',
            unitLong: 'milliliters',
          },
        },
      },
      {
        id: 1125,
        aisle: 'Milk, Eggs, Other Dairy',
        image: 'egg-yolk.jpg',
        consistency: 'SOLID',
        name: 'egg yolks',
        nameClean: 'egg yolk',
        original: '2 Egg yolks, lightly beaten',
        originalName: 'Egg yolks, lightly beaten',
        amount: 2.0,
        unit: '',
        meta: ['lightly beaten'],
        measures: {
          us: {
            amount: 2.0,
            unitShort: '',
            unitLong: '',
          },
          metric: {
            amount: 2.0,
            unitShort: '',
            unitLong: '',
          },
        },
      },
      {
        id: 1077,
        aisle: 'Milk, Eggs, Other Dairy',
        image: 'milk.png',
        consistency: 'LIQUID',
        name: 'milk',
        nameClean: 'milk',
        original: '100ml (3/4 cup) Fresh milk',
        originalName: '100ml Fresh milk',
        amount: 0.75,
        unit: 'cup',
        meta: ['fresh'],
        measures: {
          us: {
            amount: 0.75,
            unitShort: 'cups',
            unitLong: 'cups',
          },
          metric: {
            amount: 183.0,
            unitShort: 'ml',
            unitLong: 'milliliters',
          },
        },
      },
      {
        id: 1124,
        aisle: 'Milk, Eggs, Other Dairy',
        image: 'egg-white.jpg',
        consistency: 'SOLID',
        name: 'egg whites',
        nameClean: 'egg whites',
        original: '2 Egg whites',
        originalName: 'Egg whites',
        amount: 2.0,
        unit: '',
        meta: [],
        measures: {
          us: {
            amount: 2.0,
            unitShort: '',
            unitLong: '',
          },
          metric: {
            amount: 2.0,
            unitShort: '',
            unitLong: '',
          },
        },
      },
    ],
    id: 649611,
    title: 'Lemon Delicious',
    readyInMinutes: 45,
    servings: 4,
    sourceUrl: 'https://www.foodista.com/recipe/BCVWGVXY/lemon-delicious',
    image: 'https://spoonacular.com/recipeImages/649611-556x370.jpg',
    imageType: 'jpg',
    summary:
      'Lemon Delicious takes around <b>45 minutes</b> from beginning to end. For <b>71 cents per serving</b>, you get a side dish that serves 4. One serving contains <b>232 calories</b>, <b>6g of protein</b>, and <b>12g of fat</b>. It is brought to you by Foodista. 5 people were glad they tried this recipe. It is a good option if you\'re following a <b>lacto ovo vegetarian</b> diet. A mixture of self raising flour, caster sugar, egg whites, and a handful of other ingredients are all it takes to make this recipe so scrumptious. All things considered, we decided this recipe <b>deserves a spoonacular score of 19%</b>. This score is rather bad. If you like this recipe, you might also like recipes such as <a href="https://spoonacular.com/recipes/delicious-lemon-cake-715395">Delicious Lemon Cake</a>, <a href="https://spoonacular.com/recipes/lemon-delicious-pudding-1196191">Lemon Delicious Pudding</a>, and <a href="https://spoonacular.com/recipes/lemon-delicious-puddings-618428">Lemon Delicious Puddings</a>.',
    cuisines: [],
    dishTypes: ['side dish'],
    diets: ['lacto ovo vegetarian'],
    occasions: [],
    instructions:
      'Preheat oven to 180C. Lightly grease 4 ramekins (you can use a smaller ramekins)\nPlace flour, sugar and lemon zest in a large mixing bowl and whisk to combine. Make a well in the centre and pour in lemon juice and melted butter. Stir to combine, add egg yolks and mix well. Stir in milk.\nIn a separate clean small  bowl of an electric mixer (I used my Kitchen Aid mixer), whisk egg whites until stiff. Fold egg whites into batter and divide mixture evenly between ramekins. Place ramekins in a large roasting dish (I used a square cake pan), filled with cold water to come halfway up the sides of the ramekins and bake for 30-35 minutes until golden.\nGood to serve warm.',
    analyzedInstructions: [
      {
        name: '',
        steps: [
          {
            number: 1,
            step: 'Preheat oven to 180C. Lightly grease 4 ramekins (you can use a smaller ramekins)',
            ingredients: [],
            equipment: [
              {
                id: 404781,
                name: 'ramekin',
                localizedName: 'ramekin',
                image: 'ramekin.jpg',
              },
              {
                id: 404784,
                name: 'oven',
                localizedName: 'oven',
                image: 'oven.jpg',
                temperature: {
                  number: 180.0,
                  unit: 'Celsius',
                },
              },
            ],
          },
          {
            number: 2,
            step: 'Place flour, sugar and lemon zest in a large mixing bowl and whisk to combine. Make a well in the centre and pour in lemon juice and melted butter. Stir to combine, add egg yolks and mix well. Stir in milk.',
            ingredients: [
              {
                id: 9152,
                name: 'lemon juice',
                localizedName: 'lemon juice',
                image: 'lemon-juice.jpg',
              },
              {
                id: 9156,
                name: 'lemon zest',
                localizedName: 'lemon zest',
                image: 'zest-lemon.jpg',
              },
              {
                id: 1125,
                name: 'egg yolk',
                localizedName: 'egg yolk',
                image: 'egg-yolk.jpg',
              },
              {
                id: 1001,
                name: 'butter',
                localizedName: 'butter',
                image: 'butter-sliced.jpg',
              },
              {
                id: 20081,
                name: 'all purpose flour',
                localizedName: 'all purpose flour',
                image: 'flour.png',
              },
              {
                id: 19335,
                name: 'sugar',
                localizedName: 'sugar',
                image: 'sugar-in-bowl.png',
              },
              {
                id: 1077,
                name: 'milk',
                localizedName: 'milk',
                image: 'milk.png',
              },
            ],
            equipment: [
              {
                id: 405907,
                name: 'mixing bowl',
                localizedName: 'mixing bowl',
                image: 'mixing-bowl.jpg',
              },
              {
                id: 404661,
                name: 'whisk',
                localizedName: 'whisk',
                image: 'whisk.png',
              },
            ],
          },
          {
            number: 3,
            step: 'In a separate clean small  bowl of an electric mixer (I used my Kitchen Aid mixer), whisk egg whites until stiff. Fold egg whites into batter and divide mixture evenly between ramekins.',
            ingredients: [
              {
                id: 1124,
                name: 'egg whites',
                localizedName: 'egg whites',
                image: 'egg-white.jpg',
              },
            ],
            equipment: [
              {
                id: 404628,
                name: 'hand mixer',
                localizedName: 'hand mixer',
                image: 'hand-mixer.png',
              },
              {
                id: 404781,
                name: 'ramekin',
                localizedName: 'ramekin',
                image: 'ramekin.jpg',
              },
              {
                id: 404726,
                name: 'blender',
                localizedName: 'blender',
                image: 'blender.png',
              },
              {
                id: 404661,
                name: 'whisk',
                localizedName: 'whisk',
                image: 'whisk.png',
              },
              {
                id: 404783,
                name: 'bowl',
                localizedName: 'bowl',
                image: 'bowl.jpg',
              },
            ],
          },
          {
            number: 4,
            step: 'Place ramekins in a large roasting dish (I used a square cake pan), filled with cold water to come halfway up the sides of the ramekins and bake for 30-35 minutes until golden.',
            ingredients: [
              {
                id: 14412,
                name: 'water',
                localizedName: 'water',
                image: 'water.png',
              },
            ],
            equipment: [
              {
                id: 404784,
                name: 'oven',
                localizedName: 'oven',
                image: 'oven.jpg',
              },
              {
                id: 404747,
                name: 'cake form',
                localizedName: 'cake form',
                image: 'cake-pan.png',
              },
              {
                id: 404781,
                name: 'ramekin',
                localizedName: 'ramekin',
                image: 'ramekin.jpg',
              },
            ],
            length: {
              number: 35,
              unit: 'minutes',
            },
          },
          {
            number: 5,
            step: 'Good to serve warm.',
            ingredients: [],
            equipment: [],
          },
        ],
      },
    ],
    originalId: null,
    spoonacularSourceUrl: 'https://spoonacular.com/lemon-delicious-649611',
  },
];

export const recipe = {
  vegetarian: false,
  vegan: false,
  glutenFree: false,
  dairyFree: false,
  veryHealthy: false,
  cheap: false,
  veryPopular: false,
  sustainable: false,
  lowFodmap: false,
  weightWatcherSmartPoints: 2,
  gaps: 'no',
  preparationMinutes: -1,
  cookingMinutes: -1,
  aggregateLikes: 10,
  healthScore: 1,
  creditsText: 'Foodista.com – The Cooking Encyclopedia Everyone Can Edit',
  license: 'CC BY 3.0',
  sourceName: 'Foodista',
  pricePerServing: 30.58,
  extendedIngredients: [
    {
      id: 15088,
      aisle: 'Seafood',
      image: 'sardines-canned.jpg',
      consistency: 'SOLID',
      name: 'sardines',
      nameClean: 'sardines',
      original: '1 can canned sardines, drained and rough chopped',
      originalName: 'canned sardines, drained and rough chopped',
      amount: 1.0,
      unit: 'can',
      meta: ['canned', 'drained', 'chopped'],
      measures: {
        us: {
          amount: 1.0,
          unitShort: 'can',
          unitLong: 'can',
        },
        metric: {
          amount: 1.0,
          unitShort: 'can',
          unitLong: 'can',
        },
      },
    },
    {
      id: 15088,
      aisle: 'Canned and Jarred;Seafood',
      image: 'sardines-canned.jpg',
      consistency: 'SOLID',
      name: 'sardines',
      nameClean: 'sardines',
      original: '1 can canned sardines, drained and rough chopped',
      originalName: 'canned sardines, drained and rough chopped',
      amount: 1.0,
      unit: 'can',
      meta: ['canned', 'drained', 'chopped'],
      measures: {
        us: {
          amount: 1.0,
          unitShort: 'can',
          unitLong: 'can',
        },
        metric: {
          amount: 1.0,
          unitShort: 'can',
          unitLong: 'can',
        },
      },
    },
    {
      id: 11134,
      aisle: 'Produce',
      image: 'cassava.jpg',
      consistency: 'SOLID',
      name: 'cassava',
      nameClean: 'cassava',
      original: '2 cups Cassava (I used frozen)',
      originalName: 'Cassava (I used frozen)',
      amount: 2.0,
      unit: 'cups',
      meta: ['frozen', '(I used )'],
      measures: {
        us: {
          amount: 2.0,
          unitShort: 'cups',
          unitLong: 'cups',
        },
        metric: {
          amount: 412.0,
          unitShort: 'g',
          unitLong: 'grams',
        },
      },
    },
    {
      id: 1033,
      aisle: 'Cheese',
      image: 'parmesan.jpg',
      consistency: 'SOLID',
      name: 'parmesan cheese',
      nameClean: 'parmesan',
      original: '4 tablespoons Parmesan Cheese, grated',
      originalName: 'Parmesan Cheese, grated',
      amount: 4.0,
      unit: 'tablespoons',
      meta: ['grated'],
      measures: {
        us: {
          amount: 4.0,
          unitShort: 'Tbsps',
          unitLong: 'Tbsps',
        },
        metric: {
          amount: 4.0,
          unitShort: 'Tbsps',
          unitLong: 'Tbsps',
        },
      },
    },
    {
      id: 1125,
      aisle: 'Milk, Eggs, Other Dairy',
      image: 'egg-yolk.jpg',
      consistency: 'SOLID',
      name: 'egg yolks',
      nameClean: 'egg yolk',
      original: '2 Egg Yolks, beaten',
      originalName: 'Egg Yolks, beaten',
      amount: 2.0,
      unit: '',
      meta: ['beaten'],
      measures: {
        us: {
          amount: 2.0,
          unitShort: '',
          unitLong: '',
        },
        metric: {
          amount: 2.0,
          unitShort: '',
          unitLong: '',
        },
      },
    },
    {
      id: 1124,
      aisle: 'Milk, Eggs, Other Dairy',
      image: 'egg-white.jpg',
      consistency: 'SOLID',
      name: 'egg whites',
      nameClean: 'egg whites',
      original: '2 Egg Whites, whisked',
      originalName: 'Egg Whites, whisked',
      amount: 2.0,
      unit: '',
      meta: [],
      measures: {
        us: {
          amount: 2.0,
          unitShort: '',
          unitLong: '',
        },
        metric: {
          amount: 2.0,
          unitShort: '',
          unitLong: '',
        },
      },
    },
    {
      id: 18369,
      aisle: 'Baking',
      image: 'white-powder.jpg',
      consistency: 'SOLID',
      name: 'baking powder',
      nameClean: 'baking powder',
      original: '2 teaspoons Baking Powder',
      originalName: 'Baking Powder',
      amount: 2.0,
      unit: 'teaspoons',
      meta: [],
      measures: {
        us: {
          amount: 2.0,
          unitShort: 'tsps',
          unitLong: 'teaspoons',
        },
        metric: {
          amount: 2.0,
          unitShort: 'tsps',
          unitLong: 'teaspoons',
        },
      },
    },
    {
      id: 18079,
      aisle: 'Pasta and Rice',
      image: 'breadcrumbs.jpg',
      consistency: 'SOLID',
      name: 'bread crumbs',
      nameClean: 'breadcrumbs',
      original: '1 cup Plain Bread Crumbs',
      originalName: 'Plain Bread Crumbs',
      amount: 1.0,
      unit: 'cup',
      meta: ['plain'],
      measures: {
        us: {
          amount: 1.0,
          unitShort: 'cup',
          unitLong: 'cup',
        },
        metric: {
          amount: 108.0,
          unitShort: 'ml',
          unitLong: 'milliliters',
        },
      },
    },
    {
      id: 11165,
      aisle: 'Produce',
      image: 'cilantro.png',
      consistency: 'SOLID',
      name: 'cilantro',
      nameClean: 'cilantro',
      original: '1/8 cup Cilantro or Parsley, minced',
      originalName: 'Cilantro or Parsley, minced',
      amount: 0.125,
      unit: 'cup',
      meta: ['minced'],
      measures: {
        us: {
          amount: 0.125,
          unitShort: 'cups',
          unitLong: 'cups',
        },
        metric: {
          amount: 2.0,
          unitShort: 'g',
          unitLong: 'grams',
        },
      },
    },
    {
      id: 11165,
      aisle: 'Produce;Spices and Seasonings',
      image: 'cilantro.png',
      consistency: 'SOLID',
      name: 'cilantro',
      nameClean: 'cilantro',
      original: '1/8 cup Cilantro or Parsley, minced',
      originalName: 'Cilantro or Parsley, minced',
      amount: 0.125,
      unit: 'cup',
      meta: ['minced'],
      measures: {
        us: {
          amount: 0.125,
          unitShort: 'cups',
          unitLong: 'cups',
        },
        metric: {
          amount: 2.0,
          unitShort: 'g',
          unitLong: 'grams',
        },
      },
    },
    {
      id: 4582,
      aisle: 'Oil, Vinegar, Salad Dressing',
      image: 'vegetable-oil.jpg',
      consistency: 'LIQUID',
      name: 'oil',
      nameClean: 'cooking oil',
      original: 'some oil, for frying',
      originalName: '3oil, for frying',
      amount: 14.0,
      unit: 'servings',
      meta: ['for frying'],
      measures: {
        us: {
          amount: 14.0,
          unitShort: 'servings',
          unitLong: 'servings',
        },
        metric: {
          amount: 14.0,
          unitShort: 'servings',
          unitLong: 'servings',
        },
      },
    },
    {
      id: 1102047,
      aisle: 'Spices and Seasonings',
      image: 'salt-and-pepper.jpg',
      consistency: 'SOLID',
      name: 'salt& pepper',
      nameClean: 'salt and pepper',
      original: 'Salt& Pepper, to taste',
      originalName: 'Salt& Pepper, to taste',
      amount: 14.0,
      unit: 'servings',
      meta: ['to taste'],
      measures: {
        us: {
          amount: 14.0,
          unitShort: 'servings',
          unitLong: 'servings',
        },
        metric: {
          amount: 14.0,
          unitShort: 'servings',
          unitLong: 'servings',
        },
      },
    },
  ],
  id: 659270,
  title: 'Sardine Croquettes (Croquetas De Sardinas)',
  readyInMinutes: 45,
  servings: 14,
  sourceUrl:
    'https://www.foodista.com/recipe/8ZNRD8RW/sardine-croquettes-croquetas-de-sardinas',
  image: 'https://spoonacular.com/recipeImages/659270-556x370.jpg',
  imageType: 'jpg',
  summary:
    'Sardine Croquettes (Croquetas De Sardinas) is a hor d\'oeuvre that serves 14. Watching your figure? This pescatarian recipe has <b>137 calories</b>, <b>5g of protein</b>, and <b>5g of fat</b> per serving. For <b>31 cents per serving</b>, this recipe <b>covers 6%</b> of your daily requirements of vitamins and minerals. From preparation to the plate, this recipe takes around <b>45 minutes</b>. This recipe from Foodista has 10 fans. A mixture of egg whites, cassava, cilantro, and a handful of other ingredients are all it takes to make this recipe so flavorful. All things considered, we decided this recipe <b>deserves a spoonacular score of 34%</b>. This score is not so super. If you like this recipe, take a look at these similar recipes: <a href="https://spoonacular.com/recipes/croquetas-de-jamon-spanish-ham-croquettes-839612">Croquetas de Jamon (Spanish Ham Croquettes)</a>, <a href="https://spoonacular.com/recipes/croquetas-de-jamon-spanish-ham-croquettes-1248649">Croquetas de Jamon (Spanish Ham Croquettes)</a>, and <a href="https://spoonacular.com/recipes/chicken-croquettes-croquetas-de-pollo-from-spain-469868">Chicken Croquettes (Croquetas de Pollo) From \'Spain</a>.',
  cuisines: [],
  dishTypes: [
    'antipasti',
    'starter',
    'snack',
    'appetizer',
    'antipasto',
    "hor d'oeuvre",
  ],
  diets: ['pescatarian'],
  occasions: [],
  winePairing: {
    pairedWines: ['riesling', 'albarino', 'sparkling rose'],
    pairingText:
      'Riesling, Albarino, and Sparkling rosé are great choices for Sardines. Strongly flavored, oily fish like sardines pair well with these crisp white wines and sparkling wine, even rosé. One wine you could try is Pro-Bono Riesling. It has 4.3 out of 5 stars and a bottle costs about 12 dollars.',
    productMatches: [
      {
        id: 428274,
        title: 'Pro-Bono Riesling',
        description:
          'Crisp entry with a balanced body; rounded with a brilliant acidity.',
        price: '$12.0',
        imageUrl: 'https://spoonacular.com/productImages/428274-312x231.jpg',
        averageRating: 0.8600000143051147,
        ratingCount: 5.0,
        score: 0.7975000143051147,
        link: 'https://www.amazon.com/Horse-Heaven-Hills-Pro-Bono-Riesling/dp/B072FGJPY9?tag=spoonacular-20',
      },
    ],
  },
  instructions:
    '<p>I used frozen cassava because it is a time saver! So no judging. In a pot with salted water cook the cassava also known as in Spanish yuca until fork tender.</p><p>Once the cassava is cooked throughly, mash it till smooth. Then add in the sardines, cheese, egg yolks, baking powder, salt, pepper, and cilantro/parsley, mix well.</p><p>Preheat oil in frying pan. With wet hands start forming balls with the sardine batter, dip it in the egg whites then roll it in the bread crumbs, use all the batter. Fry corquettes till golden brown on all sides. Let it rest on a double-lined paper towel to remove excess oil. Serve with ketchup.</p>',
  analyzedInstructions: [
    {
      name: '',
      steps: [
        {
          number: 1,
          step: 'I used frozen cassava because it is a time saver! So no judging. In a pot with salted water cook the cassava also known as in Spanish yuca until fork tender.Once the cassava is cooked throughly, mash it till smooth. Then add in the sardines, cheese, egg yolks, baking powder, salt, pepper, and cilantro/parsley, mix well.Preheat oil in frying pan. With wet hands start forming balls with the sardine batter, dip it in the egg whites then roll it in the bread crumbs, use all the batter. Fry corquettes till golden brown on all sides.',
          ingredients: [
            {
              id: 18369,
              name: 'baking powder',
              localizedName: 'baking powder',
              image: 'white-powder.jpg',
            },
            {
              id: 18079,
              name: 'breadcrumbs',
              localizedName: 'breadcrumbs',
              image: 'breadcrumbs.jpg',
            },
            {
              id: 1124,
              name: 'egg whites',
              localizedName: 'egg whites',
              image: 'egg-white.jpg',
            },
            {
              id: 1125,
              name: 'egg yolk',
              localizedName: 'egg yolk',
              image: 'egg-yolk.jpg',
            },
            {
              id: 11165,
              name: 'cilantro',
              localizedName: 'cilantro',
              image: 'cilantro.png',
            },
            {
              id: 15088,
              name: 'sardines',
              localizedName: 'sardines',
              image: 'sardines-canned.jpg',
            },
            {
              id: 11134,
              name: 'cassava',
              localizedName: 'cassava',
              image: 'cassava.jpg',
            },
            {
              id: 11297,
              name: 'parsley',
              localizedName: 'parsley',
              image: 'parsley.jpg',
            },
            {
              id: 1041009,
              name: 'cheese',
              localizedName: 'cheese',
              image: 'cheddar-cheese.png',
            },
            {
              id: 1002030,
              name: 'pepper',
              localizedName: 'pepper',
              image: 'pepper.jpg',
            },
            {
              id: 14412,
              name: 'water',
              localizedName: 'water',
              image: 'water.png',
            },
            {
              id: 0,
              name: 'roll',
              localizedName: 'roll',
              image: 'dinner-yeast-rolls.jpg',
            },
            {
              id: 2047,
              name: 'salt',
              localizedName: 'salt',
              image: 'salt.jpg',
            },
            {
              id: 0,
              name: 'dip',
              localizedName: 'dip',
              image: '',
            },
            {
              id: 4582,
              name: 'cooking oil',
              localizedName: 'cooking oil',
              image: 'vegetable-oil.jpg',
            },
          ],
          equipment: [
            {
              id: 404645,
              name: 'frying pan',
              localizedName: 'frying pan',
              image: 'pan.png',
            },
            {
              id: 404752,
              name: 'pot',
              localizedName: 'pot',
              image: 'stock-pot.jpg',
            },
          ],
        },
        {
          number: 2,
          step: 'Let it rest on a double-lined paper towel to remove excess oil.',
          ingredients: [
            {
              id: 4582,
              name: 'cooking oil',
              localizedName: 'cooking oil',
              image: 'vegetable-oil.jpg',
            },
          ],
          equipment: [
            {
              id: 405895,
              name: 'paper towels',
              localizedName: 'paper towels',
              image: 'paper-towels.jpg',
            },
          ],
        },
        {
          number: 3,
          step: 'Serve with ketchup.',
          ingredients: [
            {
              id: 11935,
              name: 'ketchup',
              localizedName: 'ketchup',
              image: 'ketchup.png',
            },
          ],
          equipment: [],
        },
      ],
    },
  ],
  originalId: null,
  spoonacularSourceUrl:
    'https://spoonacular.com/sardine-croquettes-croquetas-de-sardinas-659270',
};
